// src/lib/components/projectShort.svelte
<script lang="ts">
  import type { Project } from "$lib/service/content/model";
	import ContentImage from "./contentImage.svelte";
	import Markdown from "./markdown.svelte";
	import ProjectHeader from "./projectHeader.svelte";
	import SpriteIcon from "./spriteIcon.svelte";

  
  export let project: Project;

  const iconSize = "1.3em"
</script>

<div class="project">

  <a href="/projects/{project.urlSafeName}"><h2>{project.name}</h2></a>
  <Markdown tokens={project.shortDescription.tokens} />
  <a href={`/projects/${project.urlSafeName}`} class="button">
    <span><SpriteIcon iconId="read-more" size={iconSize} /></span>
    Read more
  </a>
  <!-- <ProjectHeader {project} /> -->
  {#if project.image != null}
    <a class="image" href="/projects/{project.urlSafeName}">
      <ContentImage definition={project.image} />
    </a>
  {/if}
</div>

<style lang="scss">

  h2 {
    margin-top: 0.1em;
  }

  a {
    text-decoration: none;
  }

  .button {
    @include button();
    display: inline-flex;
    justify-content: center;
    flex-direction: row;

    & > span {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      margin-right: 0.5em;
    }
  }
</style>

// src/components/ProjectShort.vue
<template>
  <div>
    <div class="project__header">
      <h3 :id="project.urlSafeName" class="project__header__title">{{ project.name }}</h3>
      <ProjectTechnologyList :project="project" />
    </div>
    <p>{{ project.short }}</p>
    <router-link
      v-if="project.longMdUrl"
      :to="`/projects/${project.urlSafeName}`"
      class="button"
    >
      Read more
    </router-link>
    <a v-if="project.siteUrl" :href="project.siteUrl" class="button">Project site</a>
    <a v-if="project.gitUrl" :href="project.gitUrl" class="button">Git repository</a>
    <figure v-if="project.imgUrl !== null">
      <img :src="project.imgUrl" />
    </figure>
  </div>
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator'
import ProjectTechnologyList from './ProjectTechnologyList.vue'
import ButtonGroup from './ButtonGroup.vue'
import { Project } from '../site-data/types'

@Component({
  components: {
    ProjectTechnologyList,
    ButtonGroup
  }
})
export default class ProjectShort extends Vue {
  @Prop(undefined) project!: Project
}
</script>

<style lang="scss" scoped>
@import '../style/style.scss';

figure {
  max-width: 100%;
  margin: 0;
}

img {
  max-width: 100%;
}

.project__header {
  display: flex;
  justify-content: space-between;
  align-items: center;

  .project__header__title {
    @include h3-style();
    margin-top: 0.2em;
  }
}
</style>
