// src/ui/components/technology/TechnologyBadge.vue
<template>
  <router-link
    class="technology-badge"
    :title="p.technology.name"
    :to="`/technologies/${p.technology.urlSafeName.value}`">
    <SvgSprite :name="spriteName" />
  </router-link>
</template>

<script lang="ts">
import { Technology } from "@/content/types";
import { Exception } from "@/util/exception";
import { computed, defineComponent } from "vue";
import SvgSprite from "../util/SvgSprite.vue";


export default defineComponent({
  props: {
    technology: {
      type: Object,
      required: true
    }
  },
  setup(props, ctx) {
    const spriteName = computed(() => {
      const technology = props.technology as Technology
      return `tech-${technology.iconName.value}`
    })
    return { p: props, spriteName }
  },
  components: { SvgSprite }
})
</script>

<style lang="scss" scoped>
@import '@/ui/style/style.scss';

$icon-size: 50px;

.technology-badge {
  &,
  > svg {
    display: block;
    background-color: $primary-color;
    height: $icon-size;
    width: $icon-size;
  }
}

.technology-badge__icon {
  pointer-events: none;
  height: $icon-size;
  width: $icon-size;
}
</style>

// src/lib/components/technologyBadge.svelte
<script lang="ts">
  import type { Technology } from "$lib/service/content/model"
	import TechnologyIcon from "./spriteIcon.svelte";
	import { DEFAULT_ICON_SIZE } from "$lib/service/spriteIcons";


  export let technology: Technology
  export let size = DEFAULT_ICON_SIZE
</script>

<a
  href={`/technologies/${technology.urlSafeName}`}
  style:--icon-size={size}
  aria-label="Read about {technology.name}"
  title="Read about {technology.name}">
  <TechnologyIcon size={size} iconId={technology.icon} />
</a>

<style lang="scss">
  a {
    display: block;
    background-color: $primary-color;
    height: var(--icon-size);
    width: var(--icon-size);
  }
</style>
